/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.gui;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author erick suy - cel:51115771
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    String Consola="";
    boolean punto=true;// por default se puede poner un punto ya que el texto inicial tiene un 0
    
    public Principal() {
        
        initComponents();
        // poniendo icon
        Toolkit imageToolkit = java.awt.Toolkit.getDefaultToolkit();
        Image iconImage = imageToolkit.createImage(getClass().getResource("/com/Imagenes/log.png"));
        iconImage = iconImage.getScaledInstance(16,16,iconImage.SCALE_SMOOTH);
        ImageIcon icon = new ImageIcon(iconImage);
        this.jmItem_log.setIcon(icon);
        
        iconImage = imageToolkit.createImage(getClass().getResource("/com/Imagenes/print.png"));
        iconImage = iconImage.getScaledInstance(16,16,iconImage.SCALE_SMOOTH);
        icon = new ImageIcon(iconImage);
        this.jmItem_Imprimir.setIcon(icon);
        
        
        iconImage = imageToolkit.createImage(getClass().getResource("/com/Imagenes/print2.png"));
        iconImage = iconImage.getScaledInstance(60,60,iconImage.SCALE_SMOOTH);
        icon = new ImageIcon(iconImage);
        this.jBtn_Imprimir.setIcon(icon);
        
        
        iconImage = imageToolkit.createImage(getClass().getResource("/com/Imagenes/log2.png"));
        iconImage = iconImage.getScaledInstance(60,60,iconImage.SCALE_SMOOTH);
        icon = new ImageIcon(iconImage);
        this.jBtn_Log.setIcon(icon);
        
        
        // seteando colores a la barra de menu
        this.jM_Archivo.setForeground(Color.gray);
        this.jMenuBar_Contenedor.setBackground(Color.black);
        this.jmItem_log.setBackground(Color.gray);
        this.jmItem_Imprimir.setBackground(Color.gray);
        
        //setear el ingreso en consola
        this.jtField_Display.setText("0");
        
        this.ocultarError();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Contenedor = new javax.swing.JPanel();
        jPanel_ContenedorBts = new javax.swing.JPanel();
        jtField_Display = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jBtn_M = new javax.swing.JButton();
        jBtn_MasMenos = new javax.swing.JButton();
        jBtn_Raiz = new javax.swing.JButton();
        jBtn_Porcentaje = new javax.swing.JButton();
        jBtn_Fraccion = new javax.swing.JButton();
        jPanel_Btns = new javax.swing.JPanel();
        jBtn_CE = new javax.swing.JButton();
        jBtn_C = new javax.swing.JButton();
        jBtn7 = new javax.swing.JButton();
        jBtn8 = new javax.swing.JButton();
        jBtn9 = new javax.swing.JButton();
        jBtn4 = new javax.swing.JButton();
        jBtn5 = new javax.swing.JButton();
        jBtn6 = new javax.swing.JButton();
        jBtn1 = new javax.swing.JButton();
        jBtn2 = new javax.swing.JButton();
        jBtn3 = new javax.swing.JButton();
        jBtn_Div = new javax.swing.JButton();
        jBtn_Mul = new javax.swing.JButton();
        jBtn_Resta = new javax.swing.JButton();
        jBtn_Mas = new javax.swing.JButton();
        jBtn0 = new javax.swing.JButton();
        jBtn_Pt = new javax.swing.JButton();
        jBtn_Igual = new javax.swing.JButton();
        jButton_back = new javax.swing.JButton();
        jBtn_Imprimir = new javax.swing.JButton();
        jBtn_Log = new javax.swing.JButton();
        jSeparator_Display = new javax.swing.JSeparator();
        jLb_error = new javax.swing.JLabel();
        jMenuBar_Contenedor = new javax.swing.JMenuBar();
        jM_Archivo = new javax.swing.JMenu();
        jmItem_log = new javax.swing.JMenuItem();
        jmItem_Imprimir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DERCAS cal");
        setBackground(new java.awt.Color(7, 7, 7));
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        jPanel_Contenedor.setBackground(new java.awt.Color(1, 1, 1));
        jPanel_Contenedor.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel_ContenedorBts.setBackground(new java.awt.Color(1, 1, 1));

        javax.swing.GroupLayout jPanel_ContenedorBtsLayout = new javax.swing.GroupLayout(jPanel_ContenedorBts);
        jPanel_ContenedorBts.setLayout(jPanel_ContenedorBtsLayout);
        jPanel_ContenedorBtsLayout.setHorizontalGroup(
            jPanel_ContenedorBtsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );
        jPanel_ContenedorBtsLayout.setVerticalGroup(
            jPanel_ContenedorBtsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jtField_Display.setBackground(new java.awt.Color(1, 1, 1));
        jtField_Display.setFont(new java.awt.Font("Ubuntu", 0, 40)); // NOI18N
        jtField_Display.setForeground(new java.awt.Color(254, 254, 254));
        jtField_Display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtField_Display.setText("0");
        jtField_Display.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel1.setBackground(new java.awt.Color(1, 1, 1));

        jBtn_M.setBackground(new java.awt.Color(72, 72, 72));
        jBtn_M.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jBtn_M.setForeground(new java.awt.Color(254, 254, 254));
        jBtn_M.setText("M");
        jBtn_M.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 72, 72)));
        jBtn_M.setPreferredSize(new java.awt.Dimension(115, 75));
        jBtn_M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_MActionPerformed(evt);
            }
        });

        jBtn_MasMenos.setBackground(new java.awt.Color(72, 72, 72));
        jBtn_MasMenos.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jBtn_MasMenos.setForeground(new java.awt.Color(254, 254, 254));
        jBtn_MasMenos.setText("x^y ");
        jBtn_MasMenos.setToolTipText("");
        jBtn_MasMenos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 72, 72)));
        jBtn_MasMenos.setPreferredSize(new java.awt.Dimension(115, 75));
        jBtn_MasMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_MasMenosActionPerformed(evt);
            }
        });

        jBtn_Raiz.setBackground(new java.awt.Color(72, 72, 72));
        jBtn_Raiz.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jBtn_Raiz.setForeground(new java.awt.Color(254, 254, 254));
        jBtn_Raiz.setText("√");
        jBtn_Raiz.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 72, 72)));
        jBtn_Raiz.setPreferredSize(new java.awt.Dimension(115, 75));
        jBtn_Raiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_RaizActionPerformed(evt);
            }
        });

        jBtn_Porcentaje.setBackground(new java.awt.Color(72, 72, 72));
        jBtn_Porcentaje.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jBtn_Porcentaje.setForeground(new java.awt.Color(254, 254, 254));
        jBtn_Porcentaje.setText("%");
        jBtn_Porcentaje.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 72, 72)));
        jBtn_Porcentaje.setPreferredSize(new java.awt.Dimension(115, 75));
        jBtn_Porcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_PorcentajeActionPerformed(evt);
            }
        });

        jBtn_Fraccion.setBackground(new java.awt.Color(72, 72, 72));
        jBtn_Fraccion.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jBtn_Fraccion.setForeground(new java.awt.Color(254, 254, 254));
        jBtn_Fraccion.setText("1/X");
        jBtn_Fraccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 72, 72)));
        jBtn_Fraccion.setPreferredSize(new java.awt.Dimension(115, 75));
        jBtn_Fraccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_FraccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtn_M, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_MasMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_Raiz, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_Porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_Fraccion, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jBtn_M, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtn_MasMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtn_Raiz, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtn_Porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtn_Fraccion, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel_Btns.setBackground(new java.awt.Color(1, 1, 1));
        jPanel_Btns.setPreferredSize(new java.awt.Dimension(300, 300));

        jBtn_CE.setBackground(new java.awt.Color(72, 72, 72));
        jBtn_CE.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jBtn_CE.setForeground(new java.awt.Color(254, 254, 254));
        jBtn_CE.setText("CE");
        jBtn_CE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 72, 72)));
        jBtn_CE.setPreferredSize(new java.awt.Dimension(115, 75));
        jBtn_CE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_CEActionPerformed(evt);
            }
        });

        jBtn_C.setBackground(new java.awt.Color(72, 72, 72));
        jBtn_C.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jBtn_C.setForeground(new java.awt.Color(254, 254, 254));
        jBtn_C.setText("C");
        jBtn_C.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 72, 72)));
        jBtn_C.setPreferredSize(new java.awt.Dimension(115, 75));
        jBtn_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_CActionPerformed(evt);
            }
        });

        jBtn7.setBackground(new java.awt.Color(72, 72, 72));
        jBtn7.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jBtn7.setForeground(new java.awt.Color(254, 254, 254));
        jBtn7.setText("7");
        jBtn7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 72, 72)));
        jBtn7.setPreferredSize(new java.awt.Dimension(115, 75));
        jBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn7ActionPerformed(evt);
            }
        });

        jBtn8.setBackground(new java.awt.Color(72, 72, 72));
        jBtn8.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jBtn8.setForeground(new java.awt.Color(254, 254, 254));
        jBtn8.setText("8");
        jBtn8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 72, 72)));
        jBtn8.setPreferredSize(new java.awt.Dimension(115, 75));
        jBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn8ActionPerformed(evt);
            }
        });

        jBtn9.setBackground(new java.awt.Color(72, 72, 72));
        jBtn9.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jBtn9.setForeground(new java.awt.Color(254, 254, 254));
        jBtn9.setText("9");
        jBtn9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 72, 72)));
        jBtn9.setPreferredSize(new java.awt.Dimension(115, 75));
        jBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn9ActionPerformed(evt);
            }
        });

        jBtn4.setBackground(new java.awt.Color(72, 72, 72));
        jBtn4.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jBtn4.setForeground(new java.awt.Color(254, 254, 254));
        jBtn4.setText("4");
        jBtn4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 72, 72)));
        jBtn4.setPreferredSize(new java.awt.Dimension(115, 75));
        jBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn4ActionPerformed(evt);
            }
        });

        jBtn5.setBackground(new java.awt.Color(72, 72, 72));
        jBtn5.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jBtn5.setForeground(new java.awt.Color(254, 254, 254));
        jBtn5.setText("5");
        jBtn5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 72, 72)));
        jBtn5.setPreferredSize(new java.awt.Dimension(115, 75));
        jBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn5ActionPerformed(evt);
            }
        });

        jBtn6.setBackground(new java.awt.Color(72, 72, 72));
        jBtn6.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jBtn6.setForeground(new java.awt.Color(254, 254, 254));
        jBtn6.setText("6");
        jBtn6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 72, 72)));
        jBtn6.setPreferredSize(new java.awt.Dimension(115, 75));
        jBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn6ActionPerformed(evt);
            }
        });

        jBtn1.setBackground(new java.awt.Color(72, 72, 72));
        jBtn1.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jBtn1.setForeground(new java.awt.Color(254, 254, 254));
        jBtn1.setText("1");
        jBtn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 72, 72)));
        jBtn1.setPreferredSize(new java.awt.Dimension(115, 75));
        jBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn1ActionPerformed(evt);
            }
        });

        jBtn2.setBackground(new java.awt.Color(72, 72, 72));
        jBtn2.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jBtn2.setForeground(new java.awt.Color(254, 254, 254));
        jBtn2.setText("2");
        jBtn2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 72, 72)));
        jBtn2.setPreferredSize(new java.awt.Dimension(115, 75));
        jBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn2ActionPerformed(evt);
            }
        });

        jBtn3.setBackground(new java.awt.Color(72, 72, 72));
        jBtn3.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jBtn3.setForeground(new java.awt.Color(254, 254, 254));
        jBtn3.setText("3");
        jBtn3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 72, 72)));
        jBtn3.setPreferredSize(new java.awt.Dimension(115, 75));
        jBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn3ActionPerformed(evt);
            }
        });

        jBtn_Div.setBackground(new java.awt.Color(72, 72, 72));
        jBtn_Div.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jBtn_Div.setForeground(new java.awt.Color(254, 254, 254));
        jBtn_Div.setText("÷");
        jBtn_Div.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 72, 72)));
        jBtn_Div.setPreferredSize(new java.awt.Dimension(115, 75));
        jBtn_Div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_DivActionPerformed(evt);
            }
        });

        jBtn_Mul.setBackground(new java.awt.Color(72, 72, 72));
        jBtn_Mul.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jBtn_Mul.setForeground(new java.awt.Color(254, 254, 254));
        jBtn_Mul.setText("*");
        jBtn_Mul.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 72, 72)));
        jBtn_Mul.setPreferredSize(new java.awt.Dimension(115, 75));
        jBtn_Mul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_MulActionPerformed(evt);
            }
        });

        jBtn_Resta.setBackground(new java.awt.Color(72, 72, 72));
        jBtn_Resta.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jBtn_Resta.setForeground(new java.awt.Color(254, 254, 254));
        jBtn_Resta.setText("-");
        jBtn_Resta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 72, 72)));
        jBtn_Resta.setPreferredSize(new java.awt.Dimension(115, 75));
        jBtn_Resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_RestaActionPerformed(evt);
            }
        });

        jBtn_Mas.setBackground(new java.awt.Color(72, 72, 72));
        jBtn_Mas.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jBtn_Mas.setForeground(new java.awt.Color(254, 254, 254));
        jBtn_Mas.setText("+");
        jBtn_Mas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 72, 72)));
        jBtn_Mas.setPreferredSize(new java.awt.Dimension(115, 75));
        jBtn_Mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_MasActionPerformed(evt);
            }
        });

        jBtn0.setBackground(new java.awt.Color(72, 72, 72));
        jBtn0.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jBtn0.setForeground(new java.awt.Color(254, 254, 254));
        jBtn0.setText("0");
        jBtn0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 72, 72)));
        jBtn0.setPreferredSize(new java.awt.Dimension(200, 75));
        jBtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn0ActionPerformed(evt);
            }
        });

        jBtn_Pt.setBackground(new java.awt.Color(72, 72, 72));
        jBtn_Pt.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jBtn_Pt.setForeground(new java.awt.Color(254, 254, 254));
        jBtn_Pt.setText(",");
        jBtn_Pt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 72, 72)));
        jBtn_Pt.setPreferredSize(new java.awt.Dimension(100, 75));
        jBtn_Pt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_PtActionPerformed(evt);
            }
        });

        jBtn_Igual.setBackground(new java.awt.Color(7, 66, 122));
        jBtn_Igual.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jBtn_Igual.setForeground(new java.awt.Color(254, 254, 254));
        jBtn_Igual.setText("=");
        jBtn_Igual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 72, 72)));
        jBtn_Igual.setPreferredSize(new java.awt.Dimension(100, 75));
        jBtn_Igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_IgualActionPerformed(evt);
            }
        });

        jButton_back.setBackground(new java.awt.Color(72, 72, 72));
        jButton_back.setForeground(new java.awt.Color(254, 254, 254));
        jButton_back.setText("⌫");
        jButton_back.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 72, 72)));
        jButton_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_BtnsLayout = new javax.swing.GroupLayout(jPanel_Btns);
        jPanel_Btns.setLayout(jPanel_BtnsLayout);
        jPanel_BtnsLayout.setHorizontalGroup(
            jPanel_BtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BtnsLayout.createSequentialGroup()
                .addGroup(jPanel_BtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_BtnsLayout.createSequentialGroup()
                        .addComponent(jBtn_CE, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_C, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_back, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_BtnsLayout.createSequentialGroup()
                        .addComponent(jBtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_BtnsLayout.createSequentialGroup()
                        .addComponent(jBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_BtnsLayout.createSequentialGroup()
                        .addGroup(jPanel_BtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel_BtnsLayout.createSequentialGroup()
                                .addComponent(jBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jBtn0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_BtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBtn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtn_Pt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_BtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtn_Div, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtn_Mul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtn_Resta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtn_Mas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtn_Igual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_BtnsLayout.setVerticalGroup(
            jPanel_BtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BtnsLayout.createSequentialGroup()
                .addGroup(jPanel_BtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_BtnsLayout.createSequentialGroup()
                        .addGroup(jPanel_BtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_BtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jBtn_CE, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jBtn_C, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton_back, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_BtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_BtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_BtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_BtnsLayout.createSequentialGroup()
                        .addComponent(jBtn_Div, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_Mul, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_Resta, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_Mas, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_BtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_BtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtn_Igual, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtn_Pt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBtn_Imprimir.setBackground(new java.awt.Color(1, 1, 1));
        jBtn_Imprimir.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jBtn_Imprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtn_Imprimir.setPreferredSize(new java.awt.Dimension(80, 80));

        jBtn_Log.setBackground(new java.awt.Color(1, 1, 1));
        jBtn_Log.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jBtn_Log.setPreferredSize(new java.awt.Dimension(80, 80));

        jSeparator_Display.setBackground(new java.awt.Color(7, 66, 122));
        jSeparator_Display.setForeground(new java.awt.Color(7, 66, 122));

        jLb_error.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLb_error.setForeground(new java.awt.Color(231, 69, 69));
        jLb_error.setText("jLabel1");

        javax.swing.GroupLayout jPanel_ContenedorLayout = new javax.swing.GroupLayout(jPanel_Contenedor);
        jPanel_Contenedor.setLayout(jPanel_ContenedorLayout);
        jPanel_ContenedorLayout.setHorizontalGroup(
            jPanel_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ContenedorLayout.createSequentialGroup()
                .addGroup(jPanel_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ContenedorLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel_Btns, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ContenedorLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator_Display, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtField_Display, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLb_error))))
                .addGap(21, 21, 21)
                .addGroup(jPanel_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ContenedorLayout.createSequentialGroup()
                        .addComponent(jBtn_Log, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel_ContenedorBts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBtn_Imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_ContenedorLayout.setVerticalGroup(
            jPanel_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ContenedorLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jSeparator_Display, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtField_Display, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLb_error)
                        .addGap(24, 24, 24)
                        .addGroup(jPanel_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel_Btns, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_ContenedorLayout.createSequentialGroup()
                        .addComponent(jBtn_Imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtn_Log, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel_ContenedorBts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jMenuBar_Contenedor.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jM_Archivo.setMnemonic('A');
        jM_Archivo.setText("Archivo");

        jmItem_log.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Imagenes/log.png")));
        jmItem_log.setMnemonic('l');
        jmItem_log.setText("Log");
        jmItem_log.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jmItem_log.setBorderPainted(true);
        jmItem_log.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jmItem_log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItem_logActionPerformed(evt);
            }
        });
        jM_Archivo.add(jmItem_log);

        jmItem_Imprimir.setMnemonic('i');
        jmItem_Imprimir.setText("Imprimir");
        jmItem_Imprimir.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jmItem_Imprimir.setBorderPainted(true);
        jmItem_Imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItem_ImprimirActionPerformed(evt);
            }
        });
        jM_Archivo.add(jmItem_Imprimir);

        jMenuBar_Contenedor.add(jM_Archivo);

        setJMenuBar(jMenuBar_Contenedor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_Contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_Contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ocultarError(){
    this.jLb_error.setVisible(false);
    }
    private void jBtn_DivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_DivActionPerformed
        // TODO add your handling code here:
        //÷
        String tmp = this.jtField_Display.getText();
        boolean Encontrado=false;
        
        
        if(tmp.length()==1 && tmp.equals("0"))            
            Consola="0";        
                
        int index_ultimo = tmp.lastIndexOf('+');
        
        if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
            Encontrado=true;
        
        if(!Encontrado){
            index_ultimo = tmp.lastIndexOf('-');
            if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
                Encontrado=true;
        }
        
        if(!Encontrado){
            index_ultimo = tmp.lastIndexOf('x');
            if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
                Encontrado=true;        
        }
        
        if(!Encontrado){
            index_ultimo = tmp.lastIndexOf('÷');
            if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
                Encontrado=true;        
        }
        
        if(!Encontrado){
            index_ultimo = tmp.lastIndexOf('±');
            if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
                Encontrado=true;        
        }
        if(!Encontrado){
            index_ultimo = tmp.lastIndexOf('.');
            if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
                Encontrado=true;        
        }
        
         if(!Encontrado){
            index_ultimo = tmp.lastIndexOf('^');
            if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
                Encontrado=true;
        }
         
        if(!Encontrado){
            index_ultimo = tmp.lastIndexOf('%');
            if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
                Encontrado=true;
        }

        
        if(!Encontrado)
            Consola+="÷";
        
        this.jtField_Display.setText(Consola);
        this.punto=true;
        this.ocultarError();
    }//GEN-LAST:event_jBtn_DivActionPerformed

    private void jButton_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_backActionPerformed
        String tmp = this.jtField_Display.getText();
        if(tmp.length()==1)
            Consola="0";
        else if(tmp.length()>1){
            tmp=tmp.substring(0, tmp.length()-1);
            Consola=tmp;
        }
        
        this.jtField_Display.setText(Consola);
        this.ocultarError();
    }//GEN-LAST:event_jButton_backActionPerformed

    private void jmItem_ImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItem_ImprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmItem_ImprimirActionPerformed

    private void jBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn1ActionPerformed
        // TODO add your handling code here:
        if(this.jtField_Display.getText().equals("0"))
            Consola="1";
        else
            Consola+="1";
        this.jtField_Display.setText(Consola);        
    }//GEN-LAST:event_jBtn1ActionPerformed

    private void jBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn2ActionPerformed
        // TODO add your handling code here:
        if(this.jtField_Display.getText().equals("0"))
            Consola="2";
        else
            Consola+="2";
        this.jtField_Display.setText(Consola);
        
    }//GEN-LAST:event_jBtn2ActionPerformed

    private void jBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn3ActionPerformed
        // TODO add your handling code here:
        if(this.jtField_Display.getText().equals("0"))
            Consola="3";
        else
            Consola+="3";
        this.jtField_Display.setText(Consola);
       
    }//GEN-LAST:event_jBtn3ActionPerformed

    private void jBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn4ActionPerformed
        // TODO add your handling code here:
        if(this.jtField_Display.getText().equals("0"))
            Consola="4";
        else
            Consola+="4";
        this.jtField_Display.setText(Consola);
    }//GEN-LAST:event_jBtn4ActionPerformed

    private void jBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn5ActionPerformed
        // TODO add your handling code here:
        if(this.jtField_Display.getText().equals("0"))
            Consola="5";
        else
            Consola+="5";
        this.jtField_Display.setText(Consola);
    }//GEN-LAST:event_jBtn5ActionPerformed

    private void jBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn6ActionPerformed
        if(this.jtField_Display.getText().equals("0"))
            Consola="6";
        else
            Consola+="6";
        this.jtField_Display.setText(Consola);        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn6ActionPerformed

    private void jBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn7ActionPerformed
        // TODO add your handling code here:
        if(this.jtField_Display.getText().equals("0"))
            Consola="7";
        else
            Consola+="7";
        this.jtField_Display.setText(Consola);
    }//GEN-LAST:event_jBtn7ActionPerformed

    private void jBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn8ActionPerformed
        // TODO add your handling code here:
        if(this.jtField_Display.getText().equals("0"))
            Consola="8";
        else
            Consola+="8";
        this.jtField_Display.setText(Consola);
    }//GEN-LAST:event_jBtn8ActionPerformed

    private void jBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn9ActionPerformed
        // TODO add your handling code here:
        if(this.jtField_Display.getText().equals("0"))
            Consola="9";
        else
            Consola+="9";
        this.jtField_Display.setText(Consola);
    }//GEN-LAST:event_jBtn9ActionPerformed

    private void jBtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn0ActionPerformed
        // TODO add your handling code here:
        if(this.jtField_Display.getText().equals("0"))
            Consola="0";
        else
            Consola+="0";
        this.jtField_Display.setText(Consola);
        this.ocultarError();
    }//GEN-LAST:event_jBtn0ActionPerformed

    private void jBtn_PtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_PtActionPerformed
        // TODO add your handling code here:
        if(this.punto){
            String tmp = this.jtField_Display.getText();
            
            if(tmp.length()==1 && tmp.equals("0"))            
                Consola="0";        
            
            int index_ultimo = tmp.lastIndexOf('.');
            if(index_ultimo!=-1){ // si existe punto en la cadena
                if(index_ultimo!=(tmp.length()-1))//length-1  la ultima posicion del arreglo de string es igual al punto
                    Consola+=".";  
            }else
                Consola+=".";
            
            this.punto=false;
            
            this.jtField_Display.setText(Consola);
        }
        this.ocultarError();
    }//GEN-LAST:event_jBtn_PtActionPerformed

    private void jBtn_MulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_MulActionPerformed
        // TODO add your handling code here:
        String tmp = this.jtField_Display.getText();
        boolean Encontrado=false;
        
        
        if(tmp.length()==1 && tmp.equals("0"))            
            Consola="0";        
                
        int index_ultimo = tmp.lastIndexOf('+');
        
        if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
            Encontrado=true;
        
        if(!Encontrado){
            index_ultimo = tmp.lastIndexOf('-');
            if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
                Encontrado=true;
        }
        
        if(!Encontrado){
            index_ultimo = tmp.lastIndexOf('x');
            if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
                Encontrado=true;        
        }
        
        if(!Encontrado){
            index_ultimo = tmp.lastIndexOf('÷');
            if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
                Encontrado=true;        
        }
        
        if(!Encontrado){
            index_ultimo = tmp.lastIndexOf('±');
            if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
                Encontrado=true;        
        }
        if(!Encontrado){
            index_ultimo = tmp.lastIndexOf('.');
            if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
                Encontrado=true;        
        }
        
        
        if(!Encontrado){
            index_ultimo = tmp.lastIndexOf('^');
            if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
                Encontrado=true;
        }
        
        if(!Encontrado){
            index_ultimo = tmp.lastIndexOf('%');
            if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
                Encontrado=true;
        }

        
        if(!Encontrado)
            Consola+="x";
        
        this.jtField_Display.setText(Consola);
        this.punto=true;
        this.ocultarError();
    }//GEN-LAST:event_jBtn_MulActionPerformed

    private void jBtn_RestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_RestaActionPerformed
        // TODO add your handling code here:
        String tmp = this.jtField_Display.getText();
        boolean Encontrado=false;
        
        
        if(tmp.length()==1 && tmp.equals("0"))            
            Consola="0";        
                
        int index_ultimo = tmp.lastIndexOf('+');
        
        if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
            Encontrado=true;
        
        if(!Encontrado){
            index_ultimo = tmp.lastIndexOf('-');
            if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
                Encontrado=true;
        }
        
        if(!Encontrado){
            index_ultimo = tmp.lastIndexOf('x');
            if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
                Encontrado=true;        
        }
        
        if(!Encontrado){
            index_ultimo = tmp.lastIndexOf('÷');
            if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
                Encontrado=true;        
        }
        
        if(!Encontrado){
            index_ultimo = tmp.lastIndexOf('±');
            if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
                Encontrado=true;        
        }
        if(!Encontrado){
            index_ultimo = tmp.lastIndexOf('.');
            if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
                Encontrado=true;        
        }
        
         if(!Encontrado){
            index_ultimo = tmp.lastIndexOf('^');
            if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
                Encontrado=true;
        }
        
        if(!Encontrado){
            index_ultimo = tmp.lastIndexOf('%');
            if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
                Encontrado=true;
        }
 
         
        if(!Encontrado)
            Consola+="-";
        
        this.jtField_Display.setText(Consola);
        this.punto=true;
    }//GEN-LAST:event_jBtn_RestaActionPerformed

    private void jBtn_MasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_MasActionPerformed
        // TODO add your handling code here:
        String tmp = this.jtField_Display.getText();
        boolean Encontrado=false;
        
        
        if(tmp.length()==1 && tmp.equals("0"))            
            Consola="0";        
                
        int index_ultimo = tmp.lastIndexOf('+');
        
        if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
            Encontrado=true;
        
        if(!Encontrado){
            index_ultimo = tmp.lastIndexOf('-');
            if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
                Encontrado=true;
        }
        
        if(!Encontrado){
            index_ultimo = tmp.lastIndexOf('x');
            if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
                Encontrado=true;        
        }
        
        if(!Encontrado){
            index_ultimo = tmp.lastIndexOf('÷');
            if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
                Encontrado=true;        
        }
        
        if(!Encontrado){
            index_ultimo = tmp.lastIndexOf('±');
            if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
                Encontrado=true;        
        }
        if(!Encontrado){
            index_ultimo = tmp.lastIndexOf('.');
            if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
                Encontrado=true;        
        }
        
         if(!Encontrado){
            index_ultimo = tmp.lastIndexOf('^');
            if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
                Encontrado=true;
        }
         
        if(!Encontrado){
            index_ultimo = tmp.lastIndexOf('%');
            if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
                Encontrado=true;
        }

         
        if(!Encontrado)
            Consola+="+";
        
        
        
        this.jtField_Display.setText(Consola);
        this.punto=true;
        this.ocultarError();
    }//GEN-LAST:event_jBtn_MasActionPerformed

    private void jBtn_RaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_RaizActionPerformed
        // TODO add your handling code here:
        String tmp = this.jtField_Display.getText();
        boolean Encontrado=false;        
        
        if(tmp.length()==1 && tmp.equals("0"))            
            Consola="0";        
         
        if(!Encontrado)
            Consola+="√";
        
        this.jtField_Display.setText(Consola);
        this.punto=true;
    }//GEN-LAST:event_jBtn_RaizActionPerformed

    private void jBtn_MasMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_MasMenosActionPerformed
        // TODO add your handling code here:
        String tmp = this.jtField_Display.getText();
        boolean Encontrado=false;        
        
        if(tmp.length()==1 && tmp.equals("0"))            
            Consola="0";        
                
        int index_ultimo = tmp.lastIndexOf('+');
        
        if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
            Encontrado=true;
        
        if(!Encontrado){
            index_ultimo = tmp.lastIndexOf('-');
            if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
                Encontrado=true;
        }
        
        if(!Encontrado){
            index_ultimo = tmp.lastIndexOf('^');
            if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
                Encontrado=true;
        }
        
        if(!Encontrado){
            index_ultimo = tmp.lastIndexOf('x');
            if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
                Encontrado=true;        
        }
        
        if(!Encontrado){
            index_ultimo = tmp.lastIndexOf('÷');
            if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
                Encontrado=true;        
        }
        
        if(!Encontrado){
            index_ultimo = tmp.lastIndexOf('±');
            if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
                Encontrado=true;        
        }
        if(!Encontrado){
            index_ultimo = tmp.lastIndexOf('.');
            if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
                Encontrado=true;        
        }
        
        if(!Encontrado)
            Consola+="^";
        
        this.jtField_Display.setText(Consola);
        this.punto=true;
        this.ocultarError();
    }//GEN-LAST:event_jBtn_MasMenosActionPerformed

    private void jBtn_FraccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_FraccionActionPerformed
        // TODO add your handling code here:
        String tmp = this.jtField_Display.getText();
        boolean Encontrado=false;        
        
        if(tmp.length()==1 && tmp.equals("0")){
            Consola="0";        
            Encontrado=true;
        }else{
            char ultimo = tmp.charAt(tmp.length()-1);
            switch(ultimo){
                case '0':
                    Encontrado=true;
                break;
                case '1':
                    Encontrado=true;
                break;
                case '2':
                    Encontrado=true;
                break;
                case '3':
                    Encontrado=true;
                break;
                case '4':
                    Encontrado=true;
                break;
                case '5':
                    Encontrado=true;
                break;
                case '6':
                    Encontrado=true;
                break;
                case '7':
                    Encontrado=true;
                break;
                case '8':
                    Encontrado=true;
                break;
                case '9':
                    Encontrado=true;
                break;
                case '.':
                    Encontrado=true;
                break;
            }
        }            
            
         
        if(!Encontrado)
            Consola+="1/";
        
        this.jtField_Display.setText(Consola);
        this.punto=true;
    }//GEN-LAST:event_jBtn_FraccionActionPerformed

    private void jBtn_CEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_CEActionPerformed
        // TODO add your handling code here:
        this.ocultarError();
    }//GEN-LAST:event_jBtn_CEActionPerformed

    private void jBtn_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_CActionPerformed
        // TODO add your handling code here:
        this.ocultarError();
    }//GEN-LAST:event_jBtn_CActionPerformed

    private void jBtn_IgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_IgualActionPerformed
        // TODO add your handling code here:
        this.ocultarError();
    }//GEN-LAST:event_jBtn_IgualActionPerformed

    private void jBtn_MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_MActionPerformed
        // memoria del ultimo registro
        this.ocultarError();
    }//GEN-LAST:event_jBtn_MActionPerformed

    private void jBtn_PorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_PorcentajeActionPerformed
        // TODO add your handling code here:
         String tmp = this.jtField_Display.getText();
        boolean Encontrado=false;        
        
        if(tmp.length()==1 && tmp.equals("0"))            
            Consola="0";        
                
        int index_ultimo = tmp.lastIndexOf('+');
        
        if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
            Encontrado=true;
        
        if(!Encontrado){
            index_ultimo = tmp.lastIndexOf('-');
            if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
                Encontrado=true;
        }
        
        if(!Encontrado){
            index_ultimo = tmp.lastIndexOf('^');
            if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
                Encontrado=true;
        }
        
        if(!Encontrado){
            index_ultimo = tmp.lastIndexOf('x');
            if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
                Encontrado=true;        
        }
        
        if(!Encontrado){
            index_ultimo = tmp.lastIndexOf('÷');
            if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
                Encontrado=true;        
        }
        
        if(!Encontrado){
            index_ultimo = tmp.lastIndexOf('±');
            if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
                Encontrado=true;        
        }
        if(!Encontrado){
            index_ultimo = tmp.lastIndexOf('.');
            if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
                Encontrado=true;        
        }
        if(!Encontrado){
            index_ultimo = tmp.lastIndexOf('%');
            if(index_ultimo!=-1 && (tmp.length()-1)==index_ultimo)
                Encontrado=true;
        }
        
        if(!Encontrado)
            Consola+="%";
        
        this.jtField_Display.setText(Consola);
        this.punto=true;
        this.ocultarError();
    }//GEN-LAST:event_jBtn_PorcentajeActionPerformed

    private void jmItem_logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItem_logActionPerformed
        // TODO add your handling code here:
        frameLog l = new frameLog();
        l.setVisible(true);
    }//GEN-LAST:event_jmItem_logActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn0;
    private javax.swing.JButton jBtn1;
    private javax.swing.JButton jBtn2;
    private javax.swing.JButton jBtn3;
    private javax.swing.JButton jBtn4;
    private javax.swing.JButton jBtn5;
    private javax.swing.JButton jBtn6;
    private javax.swing.JButton jBtn7;
    private javax.swing.JButton jBtn8;
    private javax.swing.JButton jBtn9;
    private javax.swing.JButton jBtn_C;
    private javax.swing.JButton jBtn_CE;
    private javax.swing.JButton jBtn_Div;
    private javax.swing.JButton jBtn_Fraccion;
    private javax.swing.JButton jBtn_Igual;
    private javax.swing.JButton jBtn_Imprimir;
    private javax.swing.JButton jBtn_Log;
    private javax.swing.JButton jBtn_M;
    private javax.swing.JButton jBtn_Mas;
    private javax.swing.JButton jBtn_MasMenos;
    private javax.swing.JButton jBtn_Mul;
    private javax.swing.JButton jBtn_Porcentaje;
    private javax.swing.JButton jBtn_Pt;
    private javax.swing.JButton jBtn_Raiz;
    private javax.swing.JButton jBtn_Resta;
    private javax.swing.JButton jButton_back;
    private javax.swing.JLabel jLb_error;
    private javax.swing.JMenu jM_Archivo;
    private javax.swing.JMenuBar jMenuBar_Contenedor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_Btns;
    private javax.swing.JPanel jPanel_Contenedor;
    private javax.swing.JPanel jPanel_ContenedorBts;
    private javax.swing.JSeparator jSeparator_Display;
    private javax.swing.JMenuItem jmItem_Imprimir;
    private javax.swing.JMenuItem jmItem_log;
    private javax.swing.JTextField jtField_Display;
    // End of variables declaration//GEN-END:variables
}
